### ISSUE TITLE
Optionally do not mirror "alpha" ("Pre-release") versions: allow to mirror the "Latest" release

### ISSUE THREAD

**Issue by AIGeneratedUsername** [pre-commit/pre-commit-mirror-maker#146]
I've scrolled through all issues here, and I see no duplicates.

There is a workflow:
1. `pre-commit autoupdate`
2. For the https://github.com/pre-commit/mirrors-prettier I automatically get `3.0.0-alpha.0`  unreleased version which is simply broken due to the bugs and regressions introduced on the "prettier" side. 
3. I have manually rollback the version for this hook to the latest released stable version `rev: v2.7.1`.

Questions:
1. Can we by default do not update to "alpha" versions? Obviously, alpha versions may be not stable or broken.
2. If (1) is impossible: can we add `pre-commit autoupdate --stable` (or `--released`) to update to latest stable versions?
3. Is there any simple way to exclude "prettier" from the `pre-commit autoupdate` command? Or easy workaround? I just want to do not reinvent the wheel.

Versions:
- pre-commit = 2.20.0
- Python 3.10

Thanks.

**Comment by asottile** [comment]
there's a bunch of duplicates in pre-commit/pre-commit -- tags are just strings and not parsed for versions (there's no agreed upon standard versioning or naming scheme for tags and I don't want to get into parsing them).

if you don't want to autoupdate don't run autoupdate -- or use the `--repo` to select the repos you want to update -- or `git checkout -p` the repos you don't want

**Comment by ssbarnea** [comment]
@asottile I hope you are not going to hate me for adding a comment here. The reality is that you are maintaining the mirrors and by default they include pre-release tags and you do not want to add any options to prevent auto-update functionality from picking these. I read probably 20+ issues closed and locked where people were trying to find a solution for this issue, but there is none.

The auto-update feature is broken due to lack of any filtering options for version tags. I bet that this not only frustrates people but also yourself, as you keep getting bug reports from others. Telling them to search more on issue tracker is not really the most welcoming measure either but who am I to complain, in the end is a free service, so I cannot ask for my money back ;)

I hope that in the end you will accept a feature for filtering tags, even if that is per repository or just a single value for entire pre-commit config. Based on a good number of years of seeing pollution from alpha version it I doubt that updating the filter would be needed too often and the best part is that pre-commit itself would need any update.

**Comment by asottile** [comment]
my guy, read the comment directly above you
