### ISSUE TITLE
Doesn't mirror out of order versions

### ISSUE THREAD

**Issue by moolmanruan** [pre-commit/pre-commit-mirror-maker#213]
Hello, it seems that the tool doesn't mirror versions that are out of order on the target repo.

An example of this can be seen with Prettier, where the [main repo](https://github.com/prettier/prettier/tags)'s latest v3 version is 3.2.5, but the [mirror repo](https://github.com/pre-commit/mirrors-prettier/tags) only includes v3 versions up to 3.1.0, after which v4 was released on the main repo.

**Comment by moolmanruan** [comment]
I investigated a bit and it seems that the version returned by npm in the call to `npm view <package_name> --json' returned the versions in a sorted list. `pre-commit-mirror-maker` keeps track of the latest version mirrored, so if a repo already mirrored a higher version, it'll miss lower versions when they come in and the tool is rerun.

**Comment by asottile** [comment]
the current behavior is not ideal but your pr breaks basic usage of this tool.  please search around for the previous discussion on this

**Comment by ruan-rr** [comment]
> please search around for the previous discussion on this

Related issues I could find:
https://github.com/pre-commit/pre-commit-mirror-maker/issues/123 - Mentioned that backporting not supported by design
https://github.com/pre-commit/pre-commit-mirror-maker/issues/206 - Not answered
https://github.com/pre-commit/pre-commit-mirror-maker/issues/207 - Mentioned duplicates

Do you have solutions in mind to allow the rest of the prettier versions to be mirrored?
I have one more idea: Add the ability to mirror missing versions by checking the current tags in the repo and skipping all those that exist already. This could be done with a flag or automatically after a normal run.

Previous ideas:
- Order versions properly so new ones are covered. [Declined](https://github.com/pre-commit/pre-commit-mirror-maker/pull/214) This will break cases where the version was already mirrored before, and tries to get mirrored again (if it was actually released after the latest mirrored version) because of the change in version ordering.
- Adding missing versions manually. [Declined](https://github.com/pre-commit/pre-commit-mirror-maker/pull/215) Not discussed beforehand.

**Comment by asottile** [comment]
no I don't have a solution as you can see.  noone has suggested anything that works just hacks that get what they want without regard for compatibility or safety

frankly I'm just going to archive mirrors-prettier since it's not worth my trouble
